services:
  web:
    build: .
    restart: always
    container_name: 'book-shop'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookshop:/app
    ports:
      - 8000:8000