# Generated by Django 5.1.2 on 2024-10-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=1028, verbose_name='Полное имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/author/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название книги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('orders_count', models.IntegerField(verbose_name='Кол-во заказов')),
                ('stock_count', models.IntegerField(verbose_name='Оставшееся кол-во книг')),
                ('annotations', models.TextField(verbose_name='Название книги')),
                ('page_count', models.IntegerField(verbose_name='Кол-во страниц')),
                ('published_by', models.CharField(max_length=128, verbose_name='Издательство')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('cover', models.ImageField(upload_to='photos/book/')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.author')),
                ('genre', models.ManyToManyField(to='shop.genres')),
            ],
        ),
    ]
