# Generated by Django 5.1.2 on 2024-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='annotations',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='orders_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во заказов'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.PositiveIntegerField(verbose_name='Год публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock_count',
            field=models.IntegerField(default=0, verbose_name='Оставшееся кол-во книг'),
        ),
    ]
